name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "dev","master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_pipeline_with_testdata:
    name: Test
    if: "${{ github.repository == 'mpieva/quicksand' }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ['singularity', 'docker']
        flags: ['--taxlvl o']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Singularity
        uses: eWaterCycle/setup-singularity@v7

      - name: Install Nextflow
        uses: MillironX/setup-nextflow@v1

      - name: CI test of ${{matrix.flags}} on ${{matrix.profile}}
        run:  nextflow run ${GITHUB_WORKSPACE} ${{matrix.flags}} -profile test,${{matrix.profile}}
